-- part3_set_function.sql
-- 집합
-- 두 개 이상의 테이블을 합집하거나 교집합, 차집합 등
-- 이미 완성된 테이블 간에 데이터를 교차하여 
-- 새로운 테이블을 만들어내는 용도로 쓰이는 연산자다.
-- 중복된 행을 제거하며 새로운 테이블을 도출해낸다.

-- 합집합(UNION)
SELECT PLAYER_NAME, HEIGHT, WEIGHT 
FROM PLAYER WHERE HEIGHT >= 185
UNION
SELECT PLAYER_NAME, HEIGHT, WEIGHT 
FROM PLAYER WHERE WEIGHT >= 80;

SELECT DISTINCT PLAYER_NAME, HEIGHT, WEIGHT
FROM PLAYER
WHERE HEIGHT >= 185 OR WEIGHT >= 80;

-- 교집합(INTERSECT)
-- 두 테이블에서 겹치는 행에 대해서만 중복을 제거한 상태로
-- 병합시킨다.
SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY >= 10000
INTERSECT
SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80;

-- 차집합(MINUS) - EXCEPT
-- MINUS 연산자 앞에 오는 테이블의 행에서
-- 뒤에 오는 테이블과 겹치는 행을 제거한 결과를
-- 하나의 테이블로 반환한다.
SELECT PLAYER_ID, PLAYER_NAME, E_PLAYER_NAME, NICKNAME
FROM PLAYER
WHERE NICKNAME IS NOT NULL
MINUS
SELECT PLAYER_ID, PLAYER_NAME, E_PLAYER_NAME, NICKNAME
FROM PLAYER
WHERE E_PLAYER_NAME IS NOT NULL;

